### ISSUE TITLE
Concat Operation

### ISSUE THREAD

**Issue by 2ori** [titu1994/Inception-v4#3]
Hi, I'm always getting errors in the inception v4 model and the inception resnet v2 model within the concat op.

"concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 73, 73, 64), (None, 73, 73, 96)]

**Comment by titu1994** [comment]
@zorancupic Sorry that was due to incorrect concat_axis of merge operations on Tensorflow backend with image_dim_ordering = "tf". 

Just made a commit bbfce5f4316774b78a5da5f3b19d7318dacd253b which fixes this.
